<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeskVault.Domain\DeskVault.Domain.csproj" />
    <ProjectReference Include="..\DeskVault.Shared\DeskVault.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Documents\DTOs\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Documents\Mappings\" />
    <Folder Include="Services\" />
    <Folder Include="Documents\Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

</Project>
