<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeskVault.Domain\DeskVault.Domain.csproj" />
    <ProjectReference Include="..\DeskVault.Shared\DeskVault.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="DTOs\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Mappings\" />
    <Folder Include="Services\" />
    <Folder Include="Validators\" />
    <Folder Include="Queries\" />
  </ItemGroup>

</Project>
