// <auto-generated />
using System;
using DeskVault.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskVault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeskVaultDbContext))]
    [Migration("20261001060955_PersistDocumentChunkSourceLocation")]
    partial class PersistDocumentChunkSourceLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.DocumentChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessingGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceLocationEndLine")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceLocationStartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "Order")
                        .IsUnique();

                    b.ToTable("DocumentChunks", null, t =>
                        {
                            t.HasCheckConstraint("CK_DocumentChunks_SourceLocationRange", "(\"SourceLocationStartLine\" IS NULL\r\n    AND \"SourceLocationEndLine\" IS NULL)\r\nOR\r\n(\"SourceLocationStartLine\" IS NOT NULL\r\n    AND \"SourceLocationEndLine\" IS NOT NULL\r\n    AND \"SourceLocationStartLine\" > 0\r\n    AND \"SourceLocationEndLine\" >= \"SourceLocationStartLine\")");
                        });
                });

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSuccessfulProcessingGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessingGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAt");

                    b.HasIndex("Sha256Hash")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.WorkspaceDocumentMembershipEntity", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkspaceId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkspaceId", "Order")
                        .IsUnique();

                    b.ToTable("WorkspaceDocumentMemberships", (string)null);
                });

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.WorkspaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastActiveDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.DocumentChunkEntity", b =>
                {
                    b.HasOne("DeskVault.Infrastructure.Persistence.Entities.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeskVault.Infrastructure.Persistence.Entities.WorkspaceDocumentMembershipEntity", b =>
                {
                    b.HasOne("DeskVault.Infrastructure.Persistence.Entities.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeskVault.Infrastructure.Persistence.Entities.WorkspaceEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
